### ISSUE TITLE
Reject requests for Wikipedia zim files.

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimit-frontend#25]
I see a number of duplicate requests from users, but also request to zim files we generate elsewhere (ie, wikipedia_en). Zimit should check against the list of available zim files and redirect them to the user. In the case of zimit-generated files who have an expiry day, considering their relative small size it redirection could still happen if said files are less than 4-5 days old.

**Comment by rgaudin** [comment]
Hum, there are two distinct issues here. This might get stale.

As for the first one, since we don't record the *Source* of a website inside ZIMs/library, we can't check automatically. A simpler approach would be to simply reject Wikipedia or youtube or TED requests and display a special page informing about the other scraper that are most appropriate and how they should use zim-requests.

For the second one, I'm not sure. How many **exactly similar** requests from different people do we get within 7d periods? Is it worth it?
Or maybe it's identical or very similar requests from the same person, fixing mistakes as we have no cancel mechanism.

**Comment by rgaudin** [comment]
Closing in favor of #28
