### ISSUE TITLE
Show last requests

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimit-frontend#26]
The youzim.it page could have a right hand column discreetly showing the last ''completed requests'', with a link to the corresponding zim file.

**Comment by kelson42** [comment]
Why we would want that?

**Comment by Popolechien** [comment]
Two reasons:
1. To avoid duplicate requests. Since we pay for these and people don't, we might as well encourage restraint. 
2. With requests being processed one at a time if would save on queuing for something that's already available.

**Comment by Popolechien** [comment]
There was also an interesting comment from the advisory board that the page is so lean that they weren't sure what the expected outcome was (the list was their suggestion).

**Comment by kelson42** [comment]
> There was also an interesting comment from the advisory board that the page is so lean that they weren't sure what the expected outcome was (the list was their suggestion).

This should be tracked in a dedicated ticket and not jump directly to a conclusion/feature.

**Comment by kelson42** [comment]
> * To avoid duplicate requests. Since we pay for these and people don't, we might as well encourage restraint.
> 
> * With requests being processed one at a time if would save on queuing for something that's already available.

If the goal is to avoid duplicate requests, then probably we shoudl have a ticket starting from here.

The solution here has many problems:
* Most of the people don't care IMO
* It depends of the options uses (it might be similar but not the same)
* There is a privacy matter
* We don't have a performance problem for the moment and even if twice less ZIM are made, the price is the same for us as this is a dedicated hardware

**Comment by OMAREID0** [comment]
Hello, I am Omar Eid. I was reading the issues to get more familiar with the project. So, about this issue: why not rent a server with 2TB to save all the files that have been created and save every request's data (domain, link to zim file, date of creation) in our database? When the user wants to request the same domain, we return a message to the user with the old zim file and provide the date of creation. Most of the wiki pages don't get updated that much, so we will save money from requests and use this money to get servers. Later, maybe we can automate it to update all the saved zim files every month. Of course, it's better to use ORM to be safe from any SQL injection because we can't control all the links.

**Comment by Popolechien** [comment]
@OMAREID0 the first answer to your suggestion we store every request is that these 2 TB would eventually fill up (and then we'd need 2TB more, etc.). With public zimit being a free service, we probably don't want to add compounding costs over time (though I hear your argument that we'd be saving on compute). 

Then the more important issue is that people may use zimit to request protected material: we can't prevent them to, but we might not want to store that content for too long.

I had forgotten about this issue, so thanks for the ping. I'll close the ticket for the time being as there are several things that need to be discussed internally regarding zimit's way forward.
