### ISSUE TITLE
Create test.youzim.it subdomain to test zim files

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimit-frontend#39]
Currently users need to download the zim files before knowing whether their ziming worked. We could establish a library instance similar to what is available at dev.library.kiwix.org whereby users could directly check out their zim file. 

The direct address to the zim file could be provided (so that people don't get to see other zimed up files), and the file be deleted from this library after a very short time.

**Comment by rgaudin** [comment]
I both like and dislike this idea because it would be useful… but that's because our service outputs cr*p.

There's no definition of “ZIM worked” and I suppose it's something that's per-user-per-website but we should have our own _general/base_ definition as well.

The problem with this new service is that it brings a lot of constraints on us: we're then _hosting_ random content (that's a legal hazard) and we have to download them into some server (for a week I suppose) while we were just uploading it to S3 ; eventually there's the kiwix-serve resources that will be required plus the custom code to make this work.

The alternative (current situation) is:
- user clicks the download like.
- Download is most likely _short_ given our limits prevent creating very large ZIMs
- user double-clicks the ZIM and test it on Kiwix reader.

Deserves a discussion IMO

**Comment by kelson42** [comment]
@Popolechien This is a ticket which describe a dolution, but not really the problem you want to fix.

It seems to me that you assert that the ZIM creation process is iterative and that having to  download the ZIM makes each iteration pretty long... and the whole process cumbersome. Therefore this attempt to shorten it.

Did I get that right?

**Comment by Popolechien** [comment]
@kelson42 I might be an edge case as I generate the zim files from a macOS machine and need to download and transfer them to a Windows machine and then again start Kiwix-server to test them. So yeah, pretty much an attempt to shorten the whole testing process. Kiwix-android is also still not able to download/browse these files.

This being said and to @rgaudin's point I agree that we would be hosting random content, with the associated risk(s) even if said hosting is for a very limited time (we could imagine a Snapchat-like function that deletes the file once it has been viewed).

**Comment by kelson42** [comment]
> Kiwix-android is also still not able to download/browse these files.

Which version of Kiwix Android?! This is an unknown issue AFAIK. A ticket should be immediatly open if this impacts dev version.

**Comment by kelson42** [comment]
> @kelson42 I might be an edge case as I generate the zim files from a macOS machine and need to download and transfer them to a Windows machine and then again start Kiwix-server to test them.

Problem tackled with https://github.com/kiwix/kiwix-build/issues/592 and/or Zimit2

**Comment by kelson42** [comment]
> So yeah, pretty much an attempt to shorten the whole testing process. 

OK, we probably should brainstorm on this many things can be done and your proposal and maybe not the first or the easiest thing to do. Currently, there is an ongoing process to identofy why so many Zimit recipes die, I would like to go through this first.

**Comment by rgaudin** [comment]
@Popolechien:

- You can also use https://github.com/technusm1/kiwings
- That self-destructing feature seems difficult

@kelson42 I think he meant that there's no catalog integration of youzim.it in android so it requires downloading and adding to kiwix App

**Comment by Popolechien** [comment]
Got Kiwings to work, it'll do for my current use case and until zimit files work in all readers.
