### ISSUE TITLE
Farsi language toggle should indicate فارسی, not Persian

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimit-frontend#88]
_Persan_ is French, Farsi is English, but either way فارسی is the native descriptor.

**Comment by benoit74** [comment]
The question is broader than that: do we agree that we want the native label (are we sure we are capable to write all of them?), in which case we should replace `French` by `Français` as well ?

So far I've considered that we will put every label in english for simplicity (I don't know how to be sure about native labels in every language, while english ones are part of ISO), but this is not a strong argument at all. 

And to me `Persian` is the correct English label for `fa`, as standardized by ISO at least: https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?iso_639_1=fa

I do not consider the option of translating labels them on-the-fly, because it is only horrible from my experience (once you've selected a bad language by mistake, you are stuck with labels you do not understand anymore).

**Comment by Popolechien** [comment]
Well for one if you look at library.kiwix.org languages are sorted by ISO order but do display in the native label.

**Comment by benoit74** [comment]
And I find library.kiwix.org combobox terribly ugly, on a personal basis I struggle a lot to find `Français` in the middle of a list with words starting with F, S, A, N, P. 

![Image](https://github.com/user-attachments/assets/09339edb-af9b-47a6-849c-bd21233541b7)

But maybe this has already been discussed and I just need to align. My point is more: "do we agree we will do it for every languages?" since your issue is only about `Persian` but the issue is broader than that. 

@kelson42 @rgaudin any thoughts?

**Comment by Popolechien** [comment]
Well Android lists languages alphabetically but separates scripts (first latin, then cyrillic, abjad, indic, etc.)
Less aggressive on the eye maybe?

![Screenshot_20241106-174939.png](https://github.com/user-attachments/assets/1ac05e7e-02ea-4836-b20d-576f0ddfe54d)

**Comment by benoit74** [comment]
The "natural" sorting of Android application seems indeed to be the solution if we move to native labels. 

Regarding the sourcing of these native labels, I propose to use Wikidata:

Query for iso639-1 codes: https://w.wiki/BsTU

```
SELECT ?language ?languageLabel ?nativeName
WHERE {
  ?language wdt:P218 "fa".    # For ISO 639-1 code (e.g., "fr" for French)
  OPTIONAL { ?language wdt:P1705 ?nativeName }  # Property for native label
  
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
```

Query for iso639-3 codes: https://w.wiki/BsTa

```
SELECT ?language ?languageLabel ?nativeName
WHERE {
  ?language wdt:P220 "fra".   # For ISO 639-3 code (e.g., "fra" for French)
  OPTIONAL { ?language wdt:P1705 ?nativeName }  # Property for native label
  
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
```

Hopefully Wikidata will provide all needed labels, or at least we have significant chances to know where to complain ^^
