### ISSUE TITLE
Why are zimit.kiwix.org-generated zim files not delivered as a torrent link?

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimit-frontend#91]
I would expect this to be a default feature, particularly for users looking to access content because of censorship.

**Comment by rgaudin** [comment]
> particularly for users looking to access content because of censorship.

This would not help **at all** regarding censorship since those ZIMs are private and thus there can not be other peers.

We could provide torrents which would contain the HTTP download URL as a webseed. This would only help regarding download integrity. I guess given the limits, the ZIMs are all expected to be small and we did not consider this critical.

Regarding censorship, zimit still needs access to:

- zimit.kiwix.org to place the request and interact
- the wasabi bucket server we upload the ZIMs to

**Comment by Popolechien** [comment]
Ok thanks.
