### ISSUE TITLE
Identify requests by UI language

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimit-frontend#94]
Since the implementation of i18n it would be interesting to increase the granularity of the logs collected by assigning them to the interface language used for the request (ie, so that we know what Farsi speakers are more likely to try and zim up).

**Comment by rgaudin** [comment]
For the record (already mentioned this last time it was discussed), I dont think it would be a good indicator because the UI is **very simple** and the language switch is not persisted. So there's very little intensive to use it (and actual friction) if you understand what it's about.

It think that the locale of the browser is even better than this.

Depending on your actual goal (if you want to explain this better), maybe retrieving the country and/or whether it's a VPN IP (some DBs have this) might be more useful.

**Comment by Popolechien** [comment]
Ok thanks. Part of the discussion with the sponsors of Persian Zimit was the ability to identify the type of content requested by Iranian users so as to be able to build dedicated scrapers if need be.

**Comment by benoit74** [comment]
We have no way to know who is an Iranian user currently. Most Iranian users coming to us are probably from the diaspora due to censorship in the country, or they are using a VPN, but in both cases trying to guess the fact they are Iranian from their IP is not going to work. And as said by rgaudin, there is a significant chance they will use the default English of the UI which is simple enough in most cases. Not feasible from my PoV, except if they ask (and pay) for a custom deployment of the zimit-frontend + zimfarm on their own domain, in which case it would be perfectly feasible to identify the requests coming from their own domains. Probably not very hard to do on a single machine to keep costs under control. But clearly additional maintenance burden for us, so they need to pay for maintenance as well.

**Comment by Popolechien** [comment]
Thanks for the detailed feedback.
